### ISSUE TITLE
ConcurrentModificationException while printing debug string

### ISSUE THREAD

**Issue by kemenyt** [medovina/MarioAI#1]
My game crashed randomly while running around with debug mode turned on =(

```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1208)
	at java.base/java.util.TreeMap$KeyIterator.next(TreeMap.java:1262)
	at agents.controllers.MarioAIBase.debugDraw(MarioAIBase.java:124)
	at engine.VisualizationComponent.render(VisualizationComponent.java:296)
	at engine.VisualizationComponent.tick(VisualizationComponent.java:161)
	at environments.MarioEnvironment.tick(MarioEnvironment.java:193)
	at engine.MarioSimulator.run(MarioSimulator.java:86)
	at engine.MarioSimulator.run(MarioSimulator.java:109)
	at Mario.main(Mario.java:77)
```

**Comment by medovina** [comment]
Tamás, thanks for reporting this issue.  I appreciate your suggested fix, but I chose to fix this in another way.

Java sends KeyListener events to a MarioAgentBase object on the event dispatching thread.  The MarioAgentBase object forwards these events to the MarioKeyboard object, which updates the MarioInput object that holds a TreeSet of pressed keys.  This MarioInput object can be simultaneously used elsewhere in the rest of the code, which (unfortunately) runs on the main thread, which is a different thread.  So that can cause a race condition, e.g. when the code in debugDraw() is iterating over the keys in a MarioInput object.  That is the cause of the bug you reported.

Your proposed fix is not quite correct.  Inside the MarioInput class, you wrapped the TreeSet in a Collections.synchronizedNavigableSet object.  The Java API documentation for Collections.synchronizedNavigableSet says

   It is imperative that the user manually synchronize on the returned navigable set when traversing it, or any of its subSet, headSet, or tailSet views, via Iterator, Spliterator or Stream.

However you are not doing that manual synchronization when you call .stream() in debugDraw().

If you added those synchronization statements, I think it would be OK.  However, I prefer to fix this differently.  Really it makes me nervous that the MarioInput object might change at any moment while the main Mario code is using it.  So I'd rather modify MarioKeyboard.getInput() to return a clone of the MarioInput object on each tick.  That way it can't change unexpectedly anywhere in the rest of the code, such as in debugDraw().  I just committed a change that does that.  My change includes a few synchronization statements in the MarioKeyboard class to make sure that this clone operation won't collide with a KeyListener update.

This fix is still not ideal.  Even with this change, all the code in MarioAIBase.toggleKey() can still run asynchronously and potentially modify options on the fly while the rest of the code is running.  Fortunately I think that race condition will rarely be significant.  Probably the best fix would be to run **all** the Mario code on the Java event dispatching thread when the GUI is on, though that would be a larger change that I don't want to make right at this moment.  :)
